### ISSUE TITLE
registry code review

### ISSUE THREAD

**Issue by mattiaerre** [mattiaerre/pink-pineapple#1]
It'd be nice if @matteofigus can do a quick code review of this repo 😅

**Comment by matteofigus** [comment]
1) I wouldn't expose all the dependencies. Making a component able to require `dotenv` means it could read your setting secrets: https://github.com/motdotla/dotenv#path
2) I recommend removing the `refreshInterval` parameter. Given components' immutability, you don't need this. I thought some times about totally removing this in fact.
3) You may want discovery:true for allowing the UI to be shown? Not sure this registry is supposed to be only for you or for anyone
4) Last but not least, anyone would be able to publish to this any component and any version. There is the `publishAuth` parameter for setting basicAuth or any other type of auth plugin, but I would leave this to you. What's your take on this?

**Comment by mattiaerre** [comment]
this is very helpful @matteofigus 
I've done 1. 2. and 3. but not 4. as I would like to have this registry available for a talk/workshop on OC I am going to have next month during http://www.womenofsiliconvalley.com/venue ... 👍
