### ISSUE TITLE
GraphQL-ify

### ISSUE THREAD

**Issue by mattiaerre** [mattiaerre/pink-pineapple#4]
What if we had a GraphQL endpoint at the OC Registry level? Wouldn't that be cool?

https://pink-pineapple.herokuapp.com/graphql

```
{
  registry {
    baseUrl
    version
    type
  }
  components {
    name
    description
    latestVersion
    updated
    activity
    state
  }
}
```

// cc @matteofigus @chriscartlidge @nickbalestra

**Comment by matteofigus** [comment]
Consider that if your registry url is `https://pink-pineapple.herokuapp.com/` it won't be easy to create a `/graphql` endpoint as that could be a component name. Recommended is perhaps to add a prefix to the registry routes (for instance `/registry`) so that other routes could be created without interfering with the registry routes convention

**Comment by nickbalestra** [comment]
A part from being it cool, is there a real benefit you foresees in this @mattiaerre ? I'm not sure I see graphql being used in this scenario, but I'm sure I'm probably missing something from the context you envision. Look forward hearing more about this

**Comment by mattiaerre** [comment]
Let's assume that you clicked on the link above and you saw that I've already implemented it ... :sweat_smile:

@matteofigus for sure you are right but that's a routing detail, not the main purpose of this exercise :smile:

Very good question @nickbalestra and I personally see multiple benefits apart from being :cool: (which would be enough anyway but that's another story)

- A (soon will be) standard way of exposing data

- very discoverable and self-documented (graphiql)

- possibility to consume components w/ graphql clients

- new SSR and CSR scenarios because of the point above

- the possibility of building other UI consuming the graphql endpoint (what about a mobile app?)

- where is the documentation about how to use the REST endpoints of the registry?

- other ideas will come from consumers

Shall we have a conversation about this at some point before EOW?

**Comment by nickbalestra** [comment]
Thanks, those are indeed great points, so thank you a lot for them!
I'm totally down for a conversation on this!

**Comment by mattiaerre** [comment]
@nickbalestra thanks, let me send you guys a calendar invite and see what we can do

// cc @matteofigus @chriscartlidge

**Comment by mattiaerre** [comment]
are you guys still interested in having a conversation about this?

// cc @matteofigus @nickbalestra @chriscartlidge

**Comment by mattiaerre** [comment]
as per our conversation, I've created this repo where there is a middleware that exposes registry info as a graphql endpoint:

https://github.com/opencomponents/oc-registry-graphql-express-middleware

closing this issue
